core/urls.py
from django.urls import path
from core.views.common import (HomeView, dashboard,
                               AppointmentCreateView, AppointmentListView,
                               AppointmentCancelView)
from core.views.lawyers import (LawyerDashboardView, LawyerProfileCreateView,
                                LawyerProfileListView, LawyerProfileDetailView,
                                LawyerProfileUpdateView, AppointmentAcceptView)
from core.views.customers import CustomerDashboardView
from core.views.managers import (ManagerDashboardView, VerifyLawyerProfileView,
                                 UnverifyLawyerProfileView)


app_name = 'core'

urlpatterns = [
    # url: '/', name = core:home
    path('', HomeView.as_view(), name='home'),

    # url: '/managers/dashboard', name = core:manager_dashboard
    path('managers/dashboard/',
         ManagerDashboardView.as_view(), name='manager_dashboard'),

    # url: '/lawyers/dashboard/', name = core:lawyer_dashboard
    path('lawyers/dashboard/',
         LawyerDashboardView.as_view(), name='lawyer_dashboard'),

    # url: '/customers/dashboard', name = core:customer_dashboard
    path('customers/dashboard/',
         CustomerDashboardView.as_view(), name='customer_dashboard'),

    # url: '/dashboard', name = core:dashboard
    path('dashboard/', dashboard, name='dashboard'),

    # url: '/lawyers/profile/create', name = core:lawyer_dashboard
    path('lawyers/profile/create/',
         LawyerProfileCreateView.as_view(), name='lawyer_profile_create'),

    # url: '/lawyers/profile', name = core:lawyer_profile
    path('lawyers/profile/', LawyerProfileUpdateView.as_view(),
         name='lawyer_profile'),

    # url: '/lawyers/', name = core:lawyers
    path('lawyers/',
         LawyerProfileListView.as_view(), name='lawyers'),

    # url: '/lawyers/1', name = core:lawyer
    path('lawyers/<int:pk>/',
         LawyerProfileDetailView.as_view(), name='lawyer'),

    # url: '/lawyers/verify/1', name = core:verify
    path('lawyers/verify/<int:pk>/',
         VerifyLawyerProfileView.as_view(), name='verify'),

    # url: '/lawyers/unverify/1', name = core:verify
    path('lawyers/unverify/<int:pk>/',
         UnverifyLawyerProfileView.as_view(), name='unverify'),

    # url: '/appointments/1', name = core:appointment
    path('appointments/<int:pk>/',
         AppointmentCreateView.as_view(), name='appointment_create'),

    # url: '/appointments/', name = core:appointments
    path('appointments/', AppointmentListView.as_view(), name='appointments'),

    # url: '/appointments/accept/', name = core:appointment
    path('appointments/accept/<int:pk>/',
         AppointmentAcceptView.as_view(), name='appointment_accept'),

    # url: '/appointments/cancel/', name = core:appointment
    path('appointments/cancel/<int:pk>/',
         AppointmentCancelView.as_view(), name='appointment_cancel'),
]

lawyers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # With the default signup url, users can register without user_type.
    # In our User model, we've declared EMPLOYEE as the default user_type.
    # With this we avoid the security concern here. But we don't want to let
    # the user register without some extra fields like First/Last Name etc.
    # It's very important to exclude the default allauth signup url.
    # Name for this url is account_signup and if we redefine the url
    # to page_not_found, no one will be able to access this path.
    # While using page_not_found, kwargs must be used with defined exception.
    # path('accounts/signup', page_not_found,
    #      kwargs={'exception': Exception('Page not Found')}),
    # We may also use RedirectView and redirect the user to users:emp_signup.

    path('accounts/signup',
         RedirectView.as_view(
             pattern_name='users:customer_signup', permanent=False)),

    path('users/', include('users.urls', namespace='users')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    import debug_toolbar

    # For Django Debug Toolbar in debug mode.
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

    # To serve static files in debug mode
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    # To serve media files in debug mode
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/views/common.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from users.mixins import NotLawyerMixin
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView
from users.appvars import MANAGER, LAWYER, CUSTOMER
from users.decorators import user_has_address
from core.appvars import APPOINTMENT_DATE_MAX_LIMIT_IN_DAYS
from users.models import User
from core.models import Appointment
from core.forms.common import AppointmentCreateForm
from core.views.functions import email_appointment_created
from django.contrib import messages
from datetime import date


class HomeView(TemplateView):

    template_name = "core/home.html"


def dashboard(request):

    if request.user.is_authenticated:
        if request.user.user_type == MANAGER:
            return redirect('core:manager_dashboard')

        if request.user.user_type == LAWYER:
            return redirect('core:lawyer_dashboard')

        elif request.user.user_type == CUSTOMER:
            return redirect('core:customer_dashboard')

    # If user is not authenticated
    return redirect('core:home')


# This is a function, thus it can't redirect the control to another route.
# It can only return True or False.
def valid_date_time(form, request, lawyer):
    time_start = lawyer.lawyerprofile.time_start
    time_end = lawyer.lawyerprofile.time_end
    appointment_date = form.cleaned_data['date']
    time = form.cleaned_data['time']

    is_valid = True

    today = date.today()
    limit = APPOINTMENT_DATE_MAX_LIMIT_IN_DAYS

    if appointment_date < today:
        messages.warning(
            request, 'Appointment date can not be in past.')
        is_valid = False

    if abs((appointment_date - today).days) > limit:
        messages.warning(
            request, f'Appointment date must be within next {limit} days.')
        is_valid = False

    # If we display only str(time_start), it shows like 14:20:00.
    # Thus, we are taking only first 5 characters to display 14:20.
    if time < time_start or time > time_end:
        messages.warning(
            request, f'Appointment time must be between \
                {str(time_start)[:5]} and {str(time_end)[:5]}.')
        is_valid = False

    return is_valid


# One lawyer can't book appointment for another lawyer
# Customers and managers can book appointment.
@method_decorator([user_has_address], name='dispatch')
class AppointmentCreateView(LoginRequiredMixin, NotLawyerMixin,
                            UserPassesTestMixin, CreateView):
    model = Appointment
    form_class = AppointmentCreateForm

    template_name = 'core/appointment.html'

    def test_func(self):
        pk = self.kwargs['pk']

        # Selecting the user with the pk as the lawyer
        lawyer = User.objects.get(pk=pk)
        customer = self.request.user

        # Check whether the lawyer has a lawyer profile or not.
        # Check lawyer and customer are same or not.
        if hasattr(lawyer, 'lawyerprofile') and lawyer != customer:
            return True
        return False

    def form_valid(self, form):
        # We have accepted a value as pk in the url.
        pk = self.kwargs['pk']

        # Selecting the user with the pk as the lawyer
        lawyer = User.objects.get(pk=pk)
        if not valid_date_time(form, self.request, lawyer):
            # Rendering this template with the present form data
            return render(self.request,
                          'core/appointment.html', {'form': form})

        form.instance.lawyer = User.objects.get(pk=pk)

        # Saving the fee of the lawyer as the fee of this appointment
        form.instance.fee = lawyer.lawyerprofile.fee

        # Selecting the present user as the customer
        customer = self.request.user
        form.instance.customer = customer
        messages.success(self.request, 'Appointment is booked successfully.')

        # Sending email may fail.
        # Using try and except to always save the object.
        try:
            email_appointment_created(customer, lawyer, form.instance)

        # If the email is not sent, just proceed.
        except Exception:
            pass

        return super().form_valid(form)


# For customer
class AppointmentListView(LoginRequiredMixin, ListView):
    model = Appointment
    template_name = 'core/appointments.html'
    context_object_name = 'appointments'

    def get_queryset(self):
        # Returning the user if exists else 404
        user = self.request.user

        if user.is_customer:
            # All appointments of customer user with descending date ordering
            return Appointment.objects.filter(
                customer=user).order_by('-creation_time')

        elif user.is_lawyer:
            return Appointment.objects.filter(
                lawyer=user).order_by('-creation_time')

        elif user.is_manager:
            return Appointment.objects.all().order_by('-creation_time')


@method_decorator([never_cache, login_required], name='dispatch')
class AppointmentCancelView(View):
    def get(self, request, *args, **kwargs):
        appointment = get_object_or_404(Appointment, pk=self.kwargs.get('pk'))

        if (request.user == appointment.lawyer or
            request.user == appointment.customer or
                request.user.is_manager):

            if appointment.is_cancelled:
                messages.warning(request, 'Appointment is already cancelled.')

            else:
                if request.user.is_manager:
                    appointment.cancelled_by = MANAGER

                elif appointment.lawyer == request.user:
                    appointment.cancelled_by = LAWYER

                elif appointment.customer == request.user:
                    appointment.cancelled_by = CUSTOMER

                appointment.save()
                messages.success(request, 'Appointment cancelled.')
        else:
            messages.warning(request, 'Permission denied.')

        # Redirect to previous page
        return redirect(request.META.get('HTTP_REFERER', '/'))

core/views/customers.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from users.decorators import customer_required


@method_decorator([login_required, customer_required], name='dispatch')
class CustomerDashboardView(TemplateView):

    template_name = 'core/dashboard.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add in a QuerySet of all the books
        user = self.request.user
        context = {
            'msg': 'Only customers can access this page.',
            'name': user.get_full_name,
            'type': user.get_user_type_display,
        }
        return context

core/views/functions.py
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags


def email_appointment_created(customer, lawyer, form_data):
    subject = 'Appointment Booking Confirmation'

    # This format must be followed to show Lawyers as the display name.
    # The email inside the <> will be replaced with the actual email.
    sender_name = 'Lawyers <noreply@domain.com>'

    to_recipients = []

    # We don't want to share the emails of customer and lawyer.
    bcc_recipients = [customer.email, lawyer.email]

    template_name = 'core/email/appointment_created.html'
    context = {
        'customer': customer,
        'lawyer': lawyer,
        'form_data': form_data,
    }

    # render with dynamic value
    html_content = render_to_string(template_name, context)

    # Strip the html tag. So people can see the pure text at least.
    text_content = strip_tags(html_content)

    msg = EmailMultiAlternatives(subject, text_content, sender_name,
                                 to_recipients, bcc=bcc_recipients)
    msg.attach_alternative(html_content, "text/html")
    msg.send(fail_silently=False)

core/views/lawyers.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import (TemplateView, CreateView,
                                  UpdateView, DetailView, ListView)
from users.decorators import (lawyer_required, user_has_address,
                              user_has_no_lawyer_profile,
                              user_has_lawyer_profile)
from core.forms.lawyers import LawyerProfileCreateForm, LawyerProfileUpdateForm
from users.models import LawyerProfile
from core.models import Appointment
from django.contrib import messages


@method_decorator([login_required, lawyer_required], name='dispatch')
class LawyerDashboardView(TemplateView):

    template_name = 'core/dashboard.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add in a QuerySet of all the books
        user = self.request.user
        context = {
            'msg': 'Only lawyers can access this page.',
            'name': user.get_full_name,
            'type': user.get_user_type_display,
        }
        return context


# This is a function, thus it can't redirect the control to another route.
# It can only return True or False.
def valid_office_hours(form, request):
    time_start = form.cleaned_data['time_start']
    time_end = form.cleaned_data['time_end']

    if time_end <= time_start:
        messages.warning(
            request, 'Office hours start time must be smaller than end time.')
        return False

    return True


@method_decorator([login_required, lawyer_required,
                   user_has_address, user_has_no_lawyer_profile],
                  name='dispatch')
class LawyerProfileCreateView(CreateView):
    model = LawyerProfile
    form_class = LawyerProfileCreateForm

    template_name = 'core/lawyer_profile_create.html'

    def form_valid(self, form):
        if not valid_office_hours(form, self.request):
            # Rendering this template with the present form data
            return render(self.request,
                          'core/lawyer_profile_create.html', {'form': form})

        # Selecting the present user as the user of this address
        form.instance.user = self.request.user
        messages.success(self.request, 'Your lawyer profile is created!')
        return super().form_valid(form)


@method_decorator([login_required, lawyer_required, user_has_address,
                   user_has_lawyer_profile], name='dispatch')
class LawyerProfileUpdateView(UpdateView):
    model = LawyerProfile
    form_class = LawyerProfileUpdateForm
    template_name = 'core/lawyer_profile.html'

    def get_object(self):
        return self.request.user.lawyerprofile

    def form_valid(self, form):
        if not valid_office_hours(form, self.request):
            # Rendering this template with the present form data
            return render(self.request,
                          'core/lawyer_profile.html',
                          {'form': form})

        messages.success(self.request, 'Your lawyer profile is updated!')
        return super().form_valid(form)


class LawyerProfileListView(ListView):
    model = LawyerProfile
    template_name = 'core/lawyers.html'
    context_object_name = 'lawyerprofiles'
    # ordering = ['-date_created']
    # paginate_by = 5  # Posts per page


@method_decorator([login_required], name='dispatch')
class LawyerProfileDetailView(DetailView):
    model = LawyerProfile
    context_object_name = 'lawyerprofile'
    template_name = 'core/lawyer.html'


@method_decorator([never_cache, login_required, lawyer_required],
                  name='dispatch')
class AppointmentAcceptView(View):
    def get(self, request, *args, **kwargs):
        appointment = get_object_or_404(Appointment, pk=self.kwargs.get('pk'))

        if appointment.lawyer == request.user:
            if not appointment.is_accepted:
                appointment.is_accepted = True
                appointment.save()
                messages.success(request, 'Appointment accepted.')
            else:
                messages.warning(request, 'Appointment is already accepted.')

        else:
            messages.warning(request, 'Permission denied.')

        return redirect('core:appointments')

templates/core/appointment.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Appointment Booking" %}{% endblock %}

{% block content %}
<main>
    <div class="container">

        <section class="mt-4 mb-4">
            <form method="post">
                {% csrf_token %}
                <legend class="border-bottom mb-4">Appointment Booking</legend>
                {{ form|crispy }}
                <button type="submit" class="btn btn-info">{% trans "Checkout" %}</button>
            </form>
        </section>

    </div>
</main>
{% endblock %}

templates/core/appointments.html
{% extends "base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Appointments" %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-4 mb-4">
        {% for appointment in appointments %}

        <!-- col-md will form columns when the screen size >= medium -->
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 mb-4">
            <section class="text-center">
                <!-- Card -->
                <div class="card">

                    <!-- Content -->
                    <div class="card-body">
                        <!-- Name -->
                        <h6 class="card-title">
                            {# For customer, show lawyer's name #}
                            {% if user.is_customer %}
                                <i class="fas fa-layer-group"></i>
                                {{ appointment.lawyer.get_full_name }}
                                <!-- Veification icon -->
                                {% if appointment.lawyer.lawyerprofile.is_verified %}
                                    <i class="far fa-check-circle text-success"></i></i>
                                {% endif %}
                            {# For lawyer, show customer's name #}
                            {% elif user.is_lawyer %}
                                <i class="fas fa-user"></i>
                                {{ appointment.customer.get_full_name }}
                            {# For manager, show both names #}
                            {% elif user.is_manager %}
                                <i class="fas fa-layer-group"></i>
                                {{ appointment.lawyer.get_full_name }}
                                <!-- Veification icon -->
                                {% if appointment.lawyer.lawyerprofile.is_verified %}
                                    <i class="far fa-check-circle text-success"></i></i>
                                {% endif %}
                                <br>
                                <i class="fas fa-user"></i>
                                {{ appointment.customer.get_full_name }}
                            {% endif %}


                        </h4>
                        <hr>

                        <div>{{ appointment.lawyer.address }}</div> <hr>
                        <div>
                            <span class="badge badge-info">
                                <i class="far fa-clock"></i>
                                {{ appointment.date|date:'d-m-Y' }} at {{ appointment.time|date:'g:i A' }}
                            </span>
                        </div>

                        <div>
                            <span class="badge badge-secondary">
                                <i class="fas fa-hashtag"></i>
                                {{ appointment.id }}
                            </span>

                            {% if appointment.is_paid %}
                                <span class="badge badge-success">Paid</span>
                            {% else %}
                                <span class="badge badge-danger">Not Paid</span>
                            {% endif %}
                            <span class="badge badge-warning">{{ appointment.fee }}</span>

                            {% if appointment.is_cancelled_by_lawyer %}
                                <span class="badge badge-danger">Cancelled by Lawyer</span>
                            {% elif appointment.is_cancelled_by_customer %}
                                <span class="badge badge-warning">Cancelled by Customer</span>
                            {% elif appointment.is_cancelled_by_manager %}
                                <span class="badge badge-danger">Cancelled by Manager</span>
                            {% elif appointment.is_accepted %}
                                <span class="badge badge-success">Accepted</span>
                            {% else %}
                                <span class="badge badge-warning">Pending</span>
                            {% endif %}

                            {% if appointment.is_completed %}
                                <span class="badge badge-success">Completed</span>
                            {% else %}
                                <span class="badge badge-secondary">Not Completed</span>
                            {% endif %}
                        </div>
                        <hr>

                        <div>
                            {{ appointment.message }}
                        </div>

                        <div class="text-center mt-2">
                            {% if user.is_lawyer and not appointment.is_accepted%}
                                <a href="{% url 'core:appointment_accept' appointment.id %}"
                                    class="btn btn-sm btn-outline-primary" role="button">
                                    Accept
                                </a>
                            {% endif %}

                            {% if not appointment.is_cancelled%}
                                <a href="{% url 'core:appointment_cancel' appointment.id %}"
                                    class="btn btn-sm btn-outline-danger" role="button">
                                    Cancel
                                </a>
                            {% endif %}
                        </div>
                    </div>

                </div>
                <!-- Card -->
            </section>
        </div>

        {# When the list is empty #}
        {% empty %}
        <div class="col-12">
            <h4 class="text-center">
                No Appointment Yet.
            </h4>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/core/dashboard.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Dashboard" %}{% endblock %}

{% block content %}
<main>
    <div class="container my-5 py-4 z-depth-1">

        <!--Section: Content-->
        <section class="text-center px-md-5 mx-md-5 dark-grey-text">

            <h3 class="font-weight-bold mb-4">Welcome {{ name }}!</h3>
            <p class="text-muted">{{ msg }}</p>
            <p><span class="badge badge-secondary">{{ type }}</span></p>

            <a class="btn btn-primary" role="button" href="{% url 'users:profile' %}">Profile</a>

        </section>
        <!--Section: Content-->

    </div>
</main>
{% endblock %}

templates/core/lawyer.html
{% extends "base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Lawyer - "|add:lawyerprofile.user.get_full_name %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-4 mb-4">

        <!-- col-md will form columns when the screen size >= medium -->
        <div class="col-md-4">
             <!-- Card -->
             <div class="card text-center">

                <!-- Avatar -->
                <div class="avatar mx-auto white mt-4">
                    <img src="{{ lawyerprofile.user.pro_pic.url }}" class="rounded-circle img-fluid" alt="Profile Avatar">
                </div>
                <hr>

                <!-- Content -->
                <div class="card-body">
                    <!-- Name -->
                    <h4 class="card-title">
                        {{ lawyerprofile.user.get_full_name }}
                        <!-- Veification icon -->
                        {% if lawyerprofile.is_verified %}
                        <i class="far fa-check-circle text-success"></i></i>
                        {% endif %}
                    </h4>
                    {% if user.is_manager %}
                        <a href="{{lawyerprofile.document.url}}" class="btn btn-primary btn-sm">
                            <i class="far fa-file-alt"></i>
                            Official Document
                        </a>
                        {% if not lawyerprofile.is_verified %}
                        <a href="{% url 'core:verify' lawyerprofile.id %}"
                            class="btn btn-sm btn-success" role="button">
                            Verify
                        </a>
                        {% else %}
                        <a href="{% url 'core:unverify' lawyerprofile.id %}"
                            class="btn btn-sm btn-danger" role="button">
                            Unverify
                        </a>
                        {% endif %}
                    {% endif %}
                </div>

            </div>
            <!-- Card -->
        </div>

        <div class="col-md-8">
            <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <span class="badge badge-success">
                            <i class="fas fa-address-card"></i>
                            About
                        </span>
                        <div>
                            {{ lawyerprofile.about }}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <span class="badge badge-info">
                            <i class="fas fa-city"></i>
                            Address
                        </span>
                        <div>{{ lawyerprofile.user.address }}</div>
                    </li>
                    <li class="list-group-item">
                        <span class="badge badge-danger">
                            <i class="fas fa-user-clock"></i>
                            Experience
                        </span>
                        <div>{{ lawyerprofile.experience }} Years</div>
                    </li>
                    <li class="list-group-item">
                        <span class="badge badge-warning">
                            <i class="fas fa-money-bill"></i>
                            Consultation Fee
                        </span>
                        <div>{{ lawyerprofile.fee }}</div>
                    </li>
                    <li class="list-group-item">
                        <span class="badge badge-secondary">
                            <i class="far fa-clock"></i>
                            Office Hours
                        </span>
                        <div>
                            {{ lawyerprofile.time_start|date:'g:i A' }}
                            <i class="fas fa-minus"></i>
                            {{ lawyerprofile.time_end|date:'g:i A' }}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <span class="badge badge-primary">
                            <i class="fas fa-list"></i>
                            Categories
                        </span>
                        <div>
                            <!-- Generally the many-to-many field is not iterable.
                            Make it iterable by added .all at the end. -->
                            {% for category in lawyerprofile.categories.all %}
                                <span class="badge badge-success">{{ category.name }}</span>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="list-group-item">
                        {% if not user.is_lawyer %}
                            <a href="{% url 'core:appointment_create' lawyerprofile.user.id %}"
                                class="btn btn-sm btn-outline-primary" role="button">
                                Get Appointment
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

templates/core/lawyer_profile_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Create Lawyer Profile" %}{% endblock %}

{% block content %}
<main>
    <div class="container">

        {# django-money fields doesn't show errors, thus showing the error manually. #}
        {% if form.errors %}
        {% for error in form.fee.errors %}
            <div class="text-center alert alert-dismissible fade show alert-{% if messages.tags %}{{ message.tags }}{% else %}info{% endif %}"
                role="alert">

                {{error}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            {% endfor %}
        {% endif %}

        <section class="mt-4 mb-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <legend class="border-bottom mb-4">Create Lawyer Profile</legend>
                {{ form|crispy }}
                <button type="submit" class="btn btn-info">{% trans "Submit" %}</button>
            </form>
        </section>

    </div>
</main>
{% endblock %}