core/urls.py
from django.urls import path
from core.views.common import (HomeView, dashboard,
                               AppointmentCreateView, AppointmentListView,
                               AppointmentCancelView)
from core.views.lawyers import (LawyerDashboardView, LawyerProfileCreateView,
                                LawyerProfileListView, LawyerProfileDetailView,
                                LawyerProfileUpdateView, AppointmentAcceptView)
from core.views.customers import CustomerDashboardView
from core.views.managers import (ManagerDashboardView, VerifyLawyerProfileView,
                                 UnverifyLawyerProfileView)


app_name = 'core'

urlpatterns = [
    # url: '/', name = core:home
    path('', HomeView.as_view(), name='home'),

    # url: '/managers/dashboard', name = core:manager_dashboard
    path('managers/dashboard/',
         ManagerDashboardView.as_view(), name='manager_dashboard'),

    # url: '/lawyers/dashboard/', name = core:lawyer_dashboard
    path('lawyers/dashboard/',
         LawyerDashboardView.as_view(), name='lawyer_dashboard'),

    # url: '/customers/dashboard', name = core:customer_dashboard
    path('customers/dashboard/',
         CustomerDashboardView.as_view(), name='customer_dashboard'),

    # url: '/dashboard', name = core:dashboard
    path('dashboard/', dashboard, name='dashboard'),

    # url: '/lawyers/profile/create', name = core:lawyer_dashboard
    path('lawyers/profile/create/',
         LawyerProfileCreateView.as_view(), name='lawyer_profile_create'),

    # url: '/lawyers/profile', name = core:lawyer_profile
    path('lawyers/profile/', LawyerProfileUpdateView.as_view(),
         name='lawyer_profile'),

    # url: '/lawyers/', name = core:lawyers
    path('lawyers/',
         LawyerProfileListView.as_view(), name='lawyers'),

    # url: '/lawyers/1', name = core:lawyer
    path('lawyers/<int:pk>/',
         LawyerProfileDetailView.as_view(), name='lawyer'),

    # url: '/lawyers/verify/1', name = core:verify
    path('lawyers/verify/<int:pk>/',
         VerifyLawyerProfileView.as_view(), name='verify'),

    # url: '/lawyers/unverify/1', name = core:verify
    path('lawyers/unverify/<int:pk>/',
         UnverifyLawyerProfileView.as_view(), name='unverify'),

    # url: '/appointments/1', name = core:appointment
    path('appointments/<int:pk>/',
         AppointmentCreateView.as_view(), name='appointment_create'),

    # url: '/appointments/', name = core:appointments
    path('appointments/', AppointmentListView.as_view(), name='appointments'),

    # url: '/appointments/accept/', name = core:appointment
    path('appointments/accept/<int:pk>/',
         AppointmentAcceptView.as_view(), name='appointment_accept'),

    # url: '/appointments/cancel/', name = core:appointment
    path('appointments/cancel/<int:pk>/',
         AppointmentCancelView.as_view(), name='appointment_cancel'),
]

templates/base.html
{% load static %}

<!-- Bootstrap 4 Imports Start-->
{% load bootstrap4 %}   {# import bootstrap4 #}
{% bootstrap_css %}     {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
<!-- Bootstrap 4 Imports End-->

<!-- date-picker import-->
{{ form.media }}    {# Adds date-picker required JS and CSS #}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon -->
    <link rel="icon" href="{% static 'core/img/favicon/favicon.ico' %}" type="image/x-icon">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">

    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">

    <!-- Page Title -->
    <title>{% block head_title %}{% endblock head_title %}</title>

    <!-- Extra Head Tags -->
    {% block extra_head %}
    {% endblock extra_head %}
</head>

<body class="d-flex flex-column min-vh-100">

    <!-- Start your project here-->
    {% block body %}

    <!-- Navbar start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <a class="navbar-brand" href="{% url 'core:home' %}"><i class="fas fa-layer-group"></i>&nbsp;Lawyers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">

            <!-- .ml-auto is used to keep the links on the right side. -->
            <div class="navbar-nav ml-auto">

                {% if user.is_authenticated %}
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i>&nbsp;Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'users:profile' %}">
                            <i class="fas fa-user"></i>&nbsp;Profile
                        </a>

                        <!-- If the user is a lawyer -->
                        {% if user.user_type == 'L' %}

                             <!-- If the lawyer has a lawyer profile -->
                            {% if user.lawyerprofile %}
                            <a class="dropdown-item" href="{% url 'core:lawyer_profile' %}">
                                <i class="fas fa-layer-group"></i>&nbsp;Lawyer Profile
                            </a>

                            {% else %}
                            <a class="dropdown-item" href="{% url 'core:lawyer_profile_create' %}">
                                <i class="fas fa-layer-group"></i>&nbsp;Create Lawyer Profile
                            </a>
                            {% endif %}

                        {% endif %}

                        <a class="dropdown-item" href="{% url 'account_email' %}">
                            <i class="fas fa-envelope"></i>&nbsp;Emails
                        </a>
                        <a class="dropdown-item" href="{% url 'account_change_password' %}">
                            <i class="fas fa-key"></i>&nbsp;Change Password
                        </a>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">
                            <i class="fas fa-sign-out-alt"></i>&nbsp;Logout
                        </a>
                    </div>
                </div>
                <a class="nav-link" href="{% url 'core:dashboard' %}">
                    <i class="fab fa-dashcube"></i>&nbsp;Dashboard
                </a>
                <a class="nav-link" href="{% url 'core:appointments' %}">
                    <i class="far fa-calendar-check"></i>&nbsp;Appointments
                </a>

                {% else %}
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-plus"></i>&nbsp;Signup
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'users:customer_signup' %}">
                            <i class="fas fa-user"></i>&nbsp;Customer
                        </a>
                        <a class="dropdown-item" href="{% url 'users:lawyer_signup' %}">
                            <i class="fas fa-layer-group"></i>&nbsp;Lawyer
                        </a>
                    </div>
                </div>
                <a class="nav-link" href="{% url 'account_login' %}">
                    <i class="fas fa-sign-in-alt"></i>&nbsp;Login
                </a>
                {% endif %}

                <a class="nav-link" href="{% url 'core:lawyers' %}">
                    <i class="fas fa-layer-group"></i>&nbsp;Lawyers
                </a>

            </div>

        </div>
    </nav>
    <!-- Navbar end -->

    <main class="flex-fill">
        <!-- Messages with BS Dismissing Alert -->
        {% if messages %}
        {% for message in messages %}
        <div class="text-center alert alert-dismissible fade show alert-{% if messages.tags %}{{ message.tags }}{% else %}info{% endif %}"
            role="alert">

            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
        {% endfor %}
        {% endif %}

        <!-- Content -->
        {% block content %}
        {% endblock content %}

        {% endblock body %}

        <!-- Extra Body -->
        {% block extra_body %}
        {% endblock extra_body %}
        <!-- End your project here-->
    </main>

    <!-- FOOTER -->
    <footer class="container">
        <hr>
        <p class="float-right"><a href="#"><i class="fas fa-arrow-up fa-2x"></i></a></p>
        <p>&copy; 2020-2020 Lawyers &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>

</body>

</html>