core/urls.py
from django.urls import path
from core.views.common import (HomeView, dashboard,
                               AppointmentCreateView, AppointmentListView,
                               AppointmentCancelView)
from core.views.lawyers import (LawyerDashboardView, LawyerProfileCreateView,
                                LawyerProfileListView, LawyerProfileDetailView,
                                LawyerProfileUpdateView, AppointmentAcceptView)
from core.views.customers import CustomerDashboardView
from core.views.managers import (ManagerDashboardView, VerifyLawyerProfileView,
                                 UnverifyLawyerProfileView)


app_name = 'core'

urlpatterns = [
    # url: '/', name = core:home
    path('', HomeView.as_view(), name='home'),

    # url: '/managers/dashboard', name = core:manager_dashboard
    path('managers/dashboard/',
         ManagerDashboardView.as_view(), name='manager_dashboard'),

    # url: '/lawyers/dashboard/', name = core:lawyer_dashboard
    path('lawyers/dashboard/',
         LawyerDashboardView.as_view(), name='lawyer_dashboard'),

    # url: '/customers/dashboard', name = core:customer_dashboard
    path('customers/dashboard/',
         CustomerDashboardView.as_view(), name='customer_dashboard'),

    # url: '/dashboard', name = core:dashboard
    path('dashboard/', dashboard, name='dashboard'),

    # url: '/lawyers/profile/create', name = core:lawyer_dashboard
    path('lawyers/profile/create/',
         LawyerProfileCreateView.as_view(), name='lawyer_profile_create'),

    # url: '/lawyers/profile', name = core:lawyer_profile
    path('lawyers/profile/', LawyerProfileUpdateView.as_view(),
         name='lawyer_profile'),

    # url: '/lawyers/', name = core:lawyers
    path('lawyers/',
         LawyerProfileListView.as_view(), name='lawyers'),

    # url: '/lawyers/1', name = core:lawyer
    path('lawyers/<int:pk>/',
         LawyerProfileDetailView.as_view(), name='lawyer'),

    # url: '/lawyers/verify/1', name = core:verify
    path('lawyers/verify/<int:pk>/',
         VerifyLawyerProfileView.as_view(), name='verify'),

    # url: '/lawyers/unverify/1', name = core:verify
    path('lawyers/unverify/<int:pk>/',
         UnverifyLawyerProfileView.as_view(), name='unverify'),

    # url: '/appointments/1', name = core:appointment
    path('appointments/<int:pk>/',
         AppointmentCreateView.as_view(), name='appointment_create'),

    # url: '/appointments/', name = core:appointments
    path('appointments/', AppointmentListView.as_view(), name='appointments'),

    # url: '/appointments/accept/', name = core:appointment
    path('appointments/accept/<int:pk>/',
         AppointmentAcceptView.as_view(), name='appointment_accept'),

    # url: '/appointments/cancel/', name = core:appointment
    path('appointments/cancel/<int:pk>/',
         AppointmentCancelView.as_view(), name='appointment_cancel'),
]

users/urls.py
from django.urls import path
from users.views.common import profile, AddressCreateView, address_update
from users.views.lawyers import LawyerSignupView
from users.views.customers import CustomerSignupView


app_name = 'users'

urlpatterns = [
    # url: /users/profile | name: users:profile
    path('profile/', profile, name='profile'),
    path('address/new/', AddressCreateView.as_view(), name='address_create'),

    path('address/update/', address_update, name='address_update'),

    # url: /users/lawyers/signup/ | name: users:lawyer_signup
    path('lawyers/signup', LawyerSignupView.as_view(), name='lawyer_signup'),

    # url: /users/customers/signup/ | name:  users:customer_signup
    path('customers/signup',
         CustomerSignupView.as_view(), name='customer_signup'),
]

users/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django_countries.fields import CountryField
from djmoney.models.fields import MoneyField
from djmoney.models.validators import MaxMoneyValidator, MinMoneyValidator
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.core.validators import MaxValueValidator
from users.appvars import (
    MANAGER, LAWYER, CUSTOMER, USER_TYPE_CHOICES,
    FIRST_NAME_MAX_LENGTH, LAST_NAME_MAX_LENGTH,
    CATEGORY_MAX_LENGTH
)
from users.functions import (
    user_default_pro_pic, user_dir, user_dir_lawyer,
    resize_image, file_size
)


# Fields provided by default
# username, first_name, last_name, email, password
# is_staff, is_active, is_superuser, date_joined, last_login
class User(AbstractUser):
    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH, verbose_name="First Name")
    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH, verbose_name="Last Name")

    # The first option is kept empty, to show the corresponding text as
    # the first option in the dropdown
    GENDER_CHOICES = [('', 'Select'), ('F', 'Female'),
                      ('M', 'Male'), ('O', 'Other')]

    # Default user_type must be defined to enforce security
    user_type = models.CharField(max_length=1, choices=USER_TYPE_CHOICES,
                                 default=CUSTOMER, verbose_name="User Type")

    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, )

    # Using verbose_name in the form.
    pro_pic = models.ImageField(default=user_default_pro_pic,
                                upload_to=user_dir,
                                verbose_name="Profile Picture",
                                validators=[file_size])

    # Overriding the save method
    def save(self, *args, **kwargs):
        resize_image(form_data=self, field_name='pro_pic')
        super().save(*args, **kwargs)

    @property
    def is_manager(self):
        return str(self.user_type) == MANAGER

    @property
    def is_lawyer(self):
        return str(self.user_type) == LAWYER

    @property
    def is_customer(self):
        return str(self.user_type) == CUSTOMER

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'


class Address(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    flat_number = models.CharField(
        max_length=10, blank=True, verbose_name="Flat Number")
    apartment_number = models.CharField(
        max_length=10, blank=True, verbose_name="Apartment Number")

    street = models.CharField(max_length=100)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)

    # postal_code max limit 10 digits
    postal_code = models.IntegerField(
        validators=[MaxValueValidator(9999999999)],
        verbose_name="Postal Code")

    # blank_label is being used to show as the first option in the dropdown
    country = CountryField(blank_label='Select')

    def __str__(self):
        address_data = [self.flat_number, self.street,
                        self.apartment_number, self.city, self.state,
                        self.postal_code, self.country]

        # Show address with a commad between the fields.

        address = ''
        for field in address_data:
            # Add a field only if the field exists.
            if field:

                # Add comma if the address is not empty.
                if address:
                    address += ', '

                address += str(field)

        return address

    # Goes to this url after successful creation of an object of this class
    def get_absolute_url(self):
        return reverse('users:profile')


class Category(models.Model):
    name = models.CharField(max_length=CATEGORY_MAX_LENGTH)

    def __str__(self):
        return self.name


class LawyerProfile(models.Model):

    # Every lawyer can have only one lawyer profile.
    # When user is deleted, lawyer profile will be deleted.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(max_length=500)
    experience = models.IntegerField(verbose_name="Experience in Year")

    # LawyerProfile-Category has many-to-many relationship.
    # multiple lawyers can have multiple categories.
    # if category is deleted, user will not be deleted bydefault.
    categories = models.ManyToManyField(Category)

    DAYS_OF_WEEK = (
        (0, 'Monday'),
        (1, 'Tuesday'),
        (2, 'Wednesday'),
        (3, 'Thursday'),
        (4, 'Friday'),
        (5, 'Saturday'),
        (6, 'Sunday'),
    )

    days = MultiSelectField(choices=DAYS_OF_WEEK,
                            max_choices=6, verbose_name="Working Days")

    time_start = models.TimeField(verbose_name="Office Hours Start")
    time_end = models.TimeField(verbose_name="Office Hours End")

    # fee max limit 6 digits
    fee = MoneyField(max_digits=10, decimal_places=2, default_currency='EUR',
                     validators=[
                         MinMoneyValidator(0),
                         MaxMoneyValidator(400000),
                         MaxMoneyValidator({'EUR': 4000, 'USD': 4000}),
                     ],
                     verbose_name="Consultation Fee")

    # As we are using Cloudary for media storage, we can't server pdf for free
    # Thus, we are defining this field as ImageField()
    # document = models.FileField(upload_to=user_dir_lawyer,
    #                             verbose_name="Official Document",
    #                             validators=[file_size, content_type_pdf])

    document = models.ImageField(upload_to=user_dir_lawyer,
                                 verbose_name="Official Document",
                                 validators=[file_size])

    is_verified = models.BooleanField(default=False)

    # Overriding the save method
    def save(self, *args, **kwargs):
        # Resize image before upload.
        resize_image(form_data=self, field_name='document',
                     height_limit=1200, square=False)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):  # new
        return reverse('core:lawyer_profile')

users/forms/common.py
from django import forms
from users.models import User, Address


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'gender', 'pro_pic']

        # If you want to change the lebel of any field in the form.
        # labels = {
        #     "first_name": "First Name",
        #     "last_name": "Last Name"
        # }


class AddressUpdateForm(forms.ModelForm):

    class Meta:
        model = Address

        fields = ['flat_number', 'apartment_number',
                  'street', 'city', 'state', 'country']

users/forms/customers.py
from allauth.account.forms import SignupForm
from users.appvars import (
    FIRST_NAME_MAX_LENGTH, LAST_NAME_MAX_LENGTH)
from django import forms


class CustomerSignupForm(SignupForm):

    # By default email, username, password fields are loaded in the form.
    # Add these fields here and include them in the save method.
    first_name = forms.CharField(
        max_length=FIRST_NAME_MAX_LENGTH, label='First Name')
    last_name = forms.CharField(
        max_length=LAST_NAME_MAX_LENGTH, label='Last Name')

    def save(self, request):
        user = super(CustomerSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        # user_type not required as default is CUSTOMER
        user.save()
        return user

users/forms/employees.py
from allauth.account.forms import SignupForm
from users.appvars import (
    FIRST_NAME_MAX_LENGTH, LAST_NAME_MAX_LENGTH)
from django import forms


class EmployeeSignupForm(SignupForm):

    # By default email, username, password fields are loaded in the form.
    # Add these fields here and include them in the save method.
    first_name = forms.CharField(
        max_length=FIRST_NAME_MAX_LENGTH, label='First Name')
    last_name = forms.CharField(
        max_length=LAST_NAME_MAX_LENGTH, label='Last Name')

    def save(self, request):
        user = super(EmployeeSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        # user_type not required as default is EMPLOYEE
        user.save()
        return user

users/views/common.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import CreateView
from users.forms.common import UserUpdateForm, AddressUpdateForm
from users.models import Address
from django.utils.http import is_safe_url


# Common Profile View
@login_required
def profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES,
                              instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('users:profile')

    # If it's not POST, it's GET. Thus generate the form.
    else:
        form = UserUpdateForm(instance=request.user)

    context = {
        'form': form,
    }

    return render(request, 'users/profile.html', context)


class AddressCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Address
    fields = ['flat_number', 'apartment_number',
              'street', 'city', 'state', 'postal_code', 'country']

    template_name = 'users/address.html'

    def test_func(self):
        try:
            # If the user has an address, return False.
            self.request.user.address is not None
            return False
        except Exception:
            return True

    def form_valid(self, form):
        # Selecting the present user as the user of this address
        form.instance.user = self.request.user
        messages.success(self.request, 'Your address is created!')

        # To create a lawyer profile, or to book an appointment,
        # it is mandatory to have an address. While performing these
        # tasks, if the user doesn't have an address. User will be redirected
        # to AddressCreateView() with a 'next' parameter.
        # If the 'next' exists and it is save, we update the success_url.
        # If the 'next'is doesn't exists or it is not a save url,
        # by default the success_url is the source of the request.
        next_url = self.request.GET.get("next", None)
        if next_url and is_safe_url(
                url=next_url,
                allowed_hosts={self.request.get_host()},
                require_https=self.request.is_secure()):

            self.success_url = next_url

        return super().form_valid(form)


@login_required
def address_update(request):
    try:
        # If the user has an address, do the following.
        request.user.address is not None

        if request.method == 'POST':
            form = AddressUpdateForm(
                request.POST, instance=request.user.address)
            if form.is_valid():
                form.save()
                messages.success(request, 'Your address is updated!')
                return redirect('users:profile')

        # If it's not POST, it's GET. Thus generate the form.
        else:
            form = AddressUpdateForm(instance=request.user.address)

            context = {'form': form}

            return render(request, 'users/address.html', context)

    # If the user doesn't have any address
    except Exception:
        messages.warning(
            request, 'You must create an address first to update it.')
        return redirect('users:profile')

users/views/customers.py
from allauth.account.views import SignupView
from users.forms.customers import CustomerSignupForm


# Customer Signup View
class CustomerSignupView(SignupView):

    template_name = 'users/signup.html'  # Custom template is mandatory.
    form_class = CustomerSignupForm
    redirect_field_name = 'next'  # Important to redirect user if it has next url.

    # This is mandatory and is copy-pasted.
    def get_context_data(self, **kwargs):
        ret = super(CustomerSignupView, self).get_context_data(**kwargs)
        ret.update(self.kwargs)
        return ret

users/views/employees.py
from allauth.account.views import SignupView
from users.forms.employees import EmployeeSignupForm


# Employee Signup View
class EmployeeSignupView(SignupView):

    template_name = 'users/signup.html'  # Custom template is mandatory
    form_class = EmployeeSignupForm
    redirect_field_name = 'next'  # Important to redirect user if has next url

    # This is mandatory and copy-pasted
    def get_context_data(self, **kwargs):
        ret = super(EmployeeSignupView, self).get_context_data(**kwargs)
        ret.update(self.kwargs)
        return ret

users/views/lawyers.py
from allauth.account.views import SignupView
from users.forms.lawyers import LawyerSignupForm


# Lawyer Signup View
class LawyerSignupView(SignupView):

    template_name = 'users/signup.html'
    form_class = LawyerSignupForm
    redirect_field_name = 'next'  # Important to redirect user if has next url

    def get_context_data(self, **kwargs):
        ret = super(LawyerSignupView, self).get_context_data(**kwargs)
        ret.update(self.kwargs)
        return ret

users/views/managers.py
from allauth.account.views import SignupView
from users.forms.managers import ManagerSignupForm


# Manager Signup View
class ManagerSignupView(SignupView):

    template_name = 'users/signup.html'
    form_class = ManagerSignupForm
    redirect_field_name = 'next'  # Important to redirect user if has next url

    def get_context_data(self, **kwargs):
        ret = super(ManagerSignupView, self).get_context_data(**kwargs)
        ret.update(self.kwargs)
        return ret

templates/users/address.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Address" %}{% endblock %}

{% block content %}
<main>
    <div class="container">

        <section class="mt-4 mb-4">
            <form method="post">
                {% csrf_token %}
                <legend class="border-bottom mb-4">Update Address</legend>
                {{ form|crispy }}
                <button type="submit" class="btn btn-info">{% trans "Submit" %}</button>
            </form>
        </section>

    </div>
</main>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
    {% trans "Profile - "|add:user.get_full_name %}
{% endblock %}

{% block content %}
<main>
    <div class="container">

        <div class="row">

            <!-- col-md will form columns when the screen size >= medium -->
            <div class="col-md-4">
                <section class="mt-4 mb-4">
                    <!-- Card -->
                    <div class="card text-center">
                        <!-- Avatar -->
                        <div class="avatar mx-auto white mt-4">
                            <img src="{{ user.pro_pic.url }}" class="rounded-circle img-fluid" alt="Profile Avatar">
                        </div>

                        <!-- Content -->
                        <div class="card-body">
                            <!-- Name -->
                            <h4 class="card-title">{{ user.get_full_name }}</h4>
                            <hr>
                            <span class="badge badge-secondary">{{ user.get_user_type_display }}</span>
                            <span class="badge badge-info">{{ user.username }}</span>
                            <span class="badge badge-primary">{{ user.email }}</span>

                            {% if user.address %}
                            <div class="mt-2">
                                <!-- btn-block is used to occupy the full width of the card. -->
                                <a href="{% url 'users:address_update' %}" class="btn btn-secondary btn-block" role="button">
                                    {{ user.address.flat_number }},
                                    {{ user.address.street }} {{ user.address.apartment_number }},
                                    {{ user.address.city }}, {{ user.address.state }}, {{ user.address.country }}
                                </a>
                            </div>
                            {% else %}
                            <div class="mt-2">
                                <a href="{% url 'users:address_create' %}" class="btn btn-warning" role="button">
                                    Add Address
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <!-- Card -->
                </section>
            </div>

            <!-- mt-md-2 will add a top margin when the screen size >= medium -->
            <div class="col-md-8 mt-md-2">
                <section class="mb-4">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <legend class="border-bottom mb-4">Profile Info</legend>
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-info">{% trans "Update" %}</button>
                    </form>
                </section>
            </div>

        </div>

    </div>
</main>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Signup" %}{% endblock %}

{% block content %}
<main>
    <div class="container">
        <section class="mt-4 mb-4">

            <h1>{% trans "Sign Up" %}</h1>
            <p>
                {% blocktrans %}
                Already have an account? Then please <a href="{{ login_url }}">sign in</a>.
                {% endblocktrans %}
            </p>

            <form class="signup" id="signup_form" method="post">
                {% csrf_token %}

                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="form-row">
                    <div class="col">{{ form.first_name|as_crispy_field }}</div>
                    <div class="col">{{ form.last_name|as_crispy_field }}</div>
                </div>

                <div>{{ form.username|as_crispy_field }}</div>

                <div>{{ form.email|as_crispy_field }}</div>
                <div>{{ form.email2|as_crispy_field }}</div>

                <div>{{ form.password1|as_crispy_field }}</div>
                <div>{{ form.password2|as_crispy_field }}</div>

                <!-- Redirect Field -->
                {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}

                <!-- Submit button -->
                <button type="submit" class="btn btn-info btn-block">{% trans "Sign Up" %}</button>

                <hr>
                <!-- Terms of service -->
                <p>By clicking <em>Sign up</em> you agree to our <a href="" target="_blank">terms of service</a>
            </form>

        </section>
    </div>
</main>
{% endblock %}